name: log4d
description: A log library. Open command-line server application. Support as package. Can help save your flutter or dart log to file. 
version: 1.0.4
publish_to: none
# homepage: https://github.com/CaiJingLong/log4d
# author: Caijinglong <cjl_spy@163.com>

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  ansicolor: ^2.0.1
  args: ^2.0.0
  shelf: ^1.3.2
  shelf_web_socket: ^1.0.2

dev_dependencies:
  test: ^1.0.0

executables:
  log4d:
  log4d_client: